/* Auto-generated by 'vwfnt2c.py' */

#ifndef VWFNT2C_PY_FONT
#define VWFNT2C_PY_FONT

#define FONT_SPACE_WIDTH 2

extern int fontGetKerning(int c, int p);
extern int fontGetGlyph(int c, int* restrict offset, int* restrict size);

#include <stdint.h>
extern const uint8_t fontGlyphBitmaps[385];

#endif//VWFNT2C_PY_FONT
